CREATE DATABASE FILEDOWN;

CREATE TABLE CONTENIDO(
    ID int(5) AUTO_INCREMENT,
    NOMBRE varchar(50) NOT NULL,
    DESCRIPCION varchar(500) NOT NULL,
    TIPO varchar(50) NOT NULL,
    FECHA varchar(50) NOT NULL,
    RUTA_ARCHIVO varchar(500) NOT NULL,
    RUTA_URL varchar(500) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE CONTACTO(
    ID int(5) AUTO_INCREMENT,
    NOMBRE varchar(25) NOT NULL,
    CORREO varchar(50) NOT NULL,
    MENSAJE varchar(200) NOT NULL,
    PRIMARY KEY(ID)
);