CREATE DATABASE FILEDOWN;

CREATE TABLE CONTENIDO(
    ID int(5) AUTO_INCREMENT,
    NOMBRE varchar(50) NOT NULL,
    DESCRIPCION varchar(500) NOT NULL,
    GENERO varchar(50) NOT NULL,
    RUTA varchar(500) NOT NULL,
    PRIMARY KEY(ID)
);